### PR TITLE
redirect stderr to stdout in every line in script file

### LINKED ISSUE #12: Goal evaluation sometimes fails on failed query
Sometimes when a query fails, its output will be printed out of sync with the rest of the file. For example, for query `cd somewhere`, the output might be:
```
...
!!!MUMUKI-QUERY-OUTPUT!!!
1
!!!MUMUKI-GOAL-OUTPUT!!!
...
cd: somewhere: No such file or directory
```
instead of the correct:
```
...
!!!MUMUKI-QUERY-OUTPUT!!!
cd: somewhere: No such file or directory
1
...
```
causing the following regexp match to fail.

This is likely caused because when the query fails, it's output is directed to STDERR instead of STDOUT and the two become unsynced.

### LINKED ISSUE #18: Wrong result when cd to non existing dir
For example:
```bash
mkdir directorio
cd dyrectorio
```

The last command should return sth like this 
```bash
cd: no such file or directory: dyrectorio
```

Nowadays, it doesn't return anything and thats confusing.

### PR DESCRIPTION
**Pull request by julian-berbel**
This seems like a somewhat absurd solution but it's the only thing I could come up with that seems to work.
I tried doing the redirection in the command line method (doing "bash #{filename} 2>&1") but that didn't seem to work either.

I also don't know how to test this other than by hand since pretty much the problem was that this was introducing non-deterministic behavior.

Anyways, it seems to work fine now ¯\\(°_o)/¯

Fixes #12. 
Fixes #18.

### CODE REVIEW

**Review by flbulgarelli — COMMENTED** [review]
Awesome! Is it possible to add a test that performs many operations with hope it gets out of sync?

**Comment by julian-berbel** [comment]
> Awesome! Is it possible to add a test that performs many operations with hope it gets out of sync?

I added a test that's run 5 times. It might still be able to pass even without the fix but the chances are reasonably low I think. I didn't want to go overboard with it to keep the test times at a reasonable threshold too.

File: spec/try_spec.rb [hunk 1]
```diff
@@ -35,6 +35,14 @@
     it { expect(result[2][:status]).to eq :failed }
   end
 
+  context 'try with cd to invalid directory - multiple times' do
+    let(:request) { struct query: 'cat nonexistent_directory', goal: goal }
+    let(:results) { 5.times.map { hook.run! hook.compile(request) } }
```
Comment (flbulgarelli) [inline spec/try_spec.rb:40]: I changed it from `Array.new(5)` to `5.times.map` which i find more intention revealing
